service: futureceo

plugins:
  - serverless-offline
  
custom:
  serverless-offline:
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /courses
      - http: 'ANY {proxy+}'